version: "3.9"

services:
  db:
    image: postgres:16
    container_name: bledor-dbase
    restart: unless-stopped
    environment:
      POSTGRES_USER: bledor
      POSTGRES_PASSWORD: bledor_password
      POSTGRES_DB: bledor_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
